# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.7.6-browsers`
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.2-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            ENVS=$(conda env list | awk '{print $1}' )
            echo $ENVS
            if ! [[ $ENVS = *"temp-env"* ]]; then
              source /opt/conda/etc/profile.d/conda.sh
              conda create --name temp-env python=3.10
              conda activate temp-env
              pip install -e .
              pip install pylint
            else
              echo "Conda env already installed"
            fi;

      - save_cache:
          key: v1.2-dependencies-{{ checksum "setup.py" }}
          paths:
            - /opt/conda

      - run:
          name: run linter
          command: |
            source /opt/conda/etc/profile.d/conda.sh
            conda activate temp-env
            pylint wordsprobability/ --rcfile .pylintrc

      - store_artifacts:
          path: test-reports
          destination: test-reports
